### ISSUE TITLE
[Suggestion] - Allow the option to add annotations for Standalone synchrony service

### ISSUE THREAD

**Issue by athira-1142** [atlassian/data-center-helm-charts#398]
### Suggestion

We have to add annotations on the services to enable session affinity and create a health check (backend configuration). At present, we can add annotations through values.yaml only on confluence service. For standalone synchrony service, we have to add annotations after the application is deployed. 

It would be great if there is an option to add annotations on Synchrony service in values.yaml as we can manage everything through Helm.

### Product

Confluence

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by errcode1202** [comment]
Hi @athira-1142,

Thankyou for the suggestion. For context, and so we can understand better what you need, would you mind creating a PR with the changes and we can use that then as a talking point as a potential addition to `main`.

**Comment by DarthKoax** [comment]
This is a feature that we have discovered would be very helpful for us. We have run into the issue also with our build where Synchrony's health check and stickiness are configured incorrectly due to inheriting from our confluence ingress annotations. 

This is recommended by Atlassian to have stickiness on for confluence and off for synchrony, along with health check pointing to /status for confluence and /sychrony/heartbeat for synchrony. 
https://confluence.atlassian.com/confkb/how-to-configure-amazon-web-service-application-load-balancer-with-confluence-859515417.html

If [athira-1142](https://github.com/athira-1142) has not already started a PR, we may look into doing so.
