### ISSUE TITLE
[Suggestion] - Support for P1 plugins

### ISSUE THREAD

**Issue by uhagemann** [atlassian/data-center-helm-charts#612]
### Suggestion

Hi,

I've tried to add the popular [JavaMelody ](https://github.com/javamelody/jira-confluence-javamelody) plugin to a Jira DC test instance, both using jira.additionalLibraries and jira.additionalPlugins. Using jira.additionalLibraries works, but is a very bad idea from security point of view, since it works only because of an uncaught error case in the plugin. Using jira.additionalPlugins can't enable the plugin, as far as I see, because it's a P1 plugin.
Did I overlook another possibility?
If not, could you please consider supporting additional P1 plugins?

Thanks!

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
Hi @uhagemann! additionalLibraries will put the jar to tomcat's lib folder in the container, while additionalBundledPlugins will put it to `/opt/atlassian/jira/atlassian-jira/WEB-INF/atlassian-bundled-plugins` from where Jira should pick it up. Can you perhaps elaborate on things you have tried and what behavior you saw?

**Comment by uhagemann** [comment]
Hi @bianchi2 !

Yes, sure - I tried both.

If you deploy the JavaMelody jar using additionalLibraries, it will install, you will be able to use the plugin from Administration, but the JavaMelody URL will also be publicly available - which is certainly a big security hole. This is because the plugin relies on some Atlassian classes to be loadable. That's not the case when deployed to the tomcat's lib folder, leading in turn to an unhandled exception and bypassing authentication. 
If you try to deploy using additionalBundledPlugins, it can't be enabled, since (my interpretation) it's not a P2 plugin.

Hope that helps!

**Comment by bianchi2** [comment]
@uhagemann how would you install this plugin in a non containerized environment? Once installed in what directory the jar will end up?

**Comment by uhagemann** [comment]
Hi @bianchi2, according to the [docs](https://confluence.atlassian.com/adminjiraserver/important-directories-and-files-938847744.html), P1 plugins should go to `<jira-application-dir>/atlassian-jira/WEB-INF/lib/`. That's the place where also `jira-api-<version>.jar` is located. When trying with `atlas-run-standalone`, the plugin works if put into `amps-standalone-jira-<version>/target/jira/webapp/WEB-INF/lib/`. So, in the containerized version, it should go to `/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/`, I guess.

**Comment by bianchi2** [comment]
thanks @uhagemann! Yes, it makes sense to add such a mount, however, there are ways for you to do it yourself.

1. In your shared-home, create a directory called `p1-plugins`. Just exec into pod and mkdir it, so that it's like `/var/atlassian/application-data/shared-home/p1-plugins`
2. kubectl cp a jar into `/var/atlassian/application-data/shared-home/p1-plugins` - `kubectl cp hello.jar $namespace/jiran-0:/var/atlassian/application-data/shared-home/pa-plugins/hello.jar` (replace $namespace with an actual namespace and jira pod name with an actual jira pod name)
3.  Add the following to your custom values:
```
jira:
  additionalVolumeMounts:
    - name: shared-home
      mountPath: /opt/atlassian/jira/atlassian-jira/WEB-INF/lib/hello.jar
      subPath: p1-plugins/hello.jar
```

Run helm upgrade. Now, `/var/atlassian/application-data/shared-home/p1-plugins/hello.jar` from shared home will be mounted into `/opt/atlassian/jira/atlassian-jira/WEB-INF/lib` and since it resides in shared home it'll be mounted into all pods in Jira statefulset. Hope it helps.

**Comment by uhagemann** [comment]
Thank you so much, @bianchi2 , your work-around works fine! Is there a chance to place your description somewhere around [here in the user guide](https://atlassian.github.io/data-center-helm-charts/userguide/CONFIGURATION/?h=additional#additional-libraries-plugins), should someone else come across this topic?

**Comment by bianchi2** [comment]
@uhagemann I'll raise a PR to update docs. Thanks for bringing this up!

**Comment by bianchi2** [comment]
Docs PR merged. Closing the issue. @uhagemann thanks for elaboration and explanations 🙇
